version: '3.7'
services:
  gate-simulator:
    build: gate-simulator/
    command: npm start
    ports:
      - "9999:9999"
  postgres:
    image: postgres:12-alpine3.15
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
